name: Deploy via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to DreamHost via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: iad1-shared-b7-28.dreamhost.com
          username: dh_qz8z3m
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: "./"
          remote_path: "filmsocialclub.io/"
          port: 22
          sftp_only: true
          delete: false     # evita borrar archivos en el servidor
